In [9]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
# sentences using for the word embedding
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
### Vocabulary size
voc_size=10000

### One_hot representation

In [7]:
onehot_rep = [one_hot(word, voc_size) for word in sent]
print(onehot_rep)

[[7357, 5997, 651, 266], [7357, 5997, 651, 3068], [7357, 4837, 651, 8047], [9740, 3377, 4620, 1469, 407], [9740, 3377, 4620, 1469, 9774], [5609, 7357, 6717, 651, 6918], [4317, 2873, 7114, 1469]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [10]:
sent_length = 8
padded_docs = pad_sequences(onehot_rep, padding = "pre", maxlen = sent_length)
print(padded_docs)

[[   0    0    0    0 7357 5997  651  266]
 [   0    0    0    0 7357 5997  651 3068]
 [   0    0    0    0 7357 4837  651 8047]
 [   0    0    0 9740 3377 4620 1469  407]
 [   0    0    0 9740 3377 4620 1469 9774]
 [   0    0    0 5609 7357 6717  651 6918]
 [   0    0    0    0 4317 2873 7114 1469]]


In [11]:
dim=10

In [ ]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile("adam", "mse")